select 
    a.event_id,
    a.user_pseudo_id,
    a.user_id,
    a.event_date,
    a.event_time,
    a.event_name,
    a.ga_session_id,
    a.engagement_time_msec,
    a.percent_scrolled,
    a.page_location,
    a.page_referrer,
    a.traffic_source_name,
    a.traffic_source_medium,
    a.traffic_source_site,
    a.device_category,
    a.device_operating_system,
    a.device_web_info_browser,
    a.geo_country,
    a.geo_region,
    a.geo_city,
    a.match_user_id,

from {{ref('final_ga')}} a left join 