
version: 2

models:

    - name: dedup_events
      description: "Source table for other models. Takes all data from `events_` and (if available) `events_intraday_` tables and deduplicates by user_pseudo_id, event_name and event_timestamp."

    - name: pageviews_proc
      description: "Flattening the `pageviews` event into rows.  All columns named as they appear in the `events_` table."

    - name: user_page_paths
      description: "Supports page path sequence reporting. Tags each pageview event from `pageviews_proc` with a `session_event_order`."
      columns:
          - name: session_event_order
            description: "Pageview number for the session"
            tests:
                - not_null
          - name: user_type
            description: "New vs existing, based on `user_first_touch_timestamp`."
    - name: stg_events_customized
      description: "ga데이터를 staging하고 unique한 id를 추가한 테이블."
      columns:
          - name: event_id
            description: "같은시간, 같은 유저, 같은 이벤트에 순서를 붙여 join key 생성"
            tests:
                - not_null
                - unique
sources:
  - name: ga_events
    database: maderi-cdp
    schema: analytics_291350587
    tables: 
      - name: events_*